version: '3.8'
services:
  # Backend service
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    networks:
      - hokoki-ai-network

  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - hokoki-ai-network

# Named volume for MongoDB data
volumes:
  mongo-data:

# Define a custom network
networks:
  hokoki-ai-network:
    driver: bridge
